### ISSUE TITLE
Stash error generated from backupconfiguration.yaml in stable/templates/postgresql

### ISSUE THREAD

**Issue by proutrc** [olcf/slate-helm-charts#30]
Here is the error we observed:

```
Error creating: admission webhook "validating-webhook.openpolicyagent.org" denied the request: Enforced: Cannot set  securityContext.runAsUser = 65535 because it does not match namespace annotation: ccs.ornl.gov/runAsUser = 2001170
```

The behavior is also odd because the pods will spin up periodically, then get knocked out (over and over).  We can see the cycle in the events tab of the Onyx cluster GUI (going up and down, while spitting out the above error).

Working with the NCCS Platforms team did result in finding the issue, which I will also bring up here.

It appears the `runtimeSettings` need to be set like this in the stable/postgresql/template/backupconfiguration.yaml file:

```
runtimeSettings:
    pod:
      securityContext:
        runAsUser: {{ include "library.runAsUser" . }}
```
Instead of this (what it currently is):

```
runtimeSettings:
    container:
      securityContext:
        runAsUser: {{ include "library.runAsUser" . }}
```

This will also be important to note for any other backup configuration files.

Here is a PR that Kellen submitted: https://github.com/olcf/slate-helm-charts/pull/29/commits
